FROM		ubi7
MAINTAINER	Rockenstein Gábor <rockensteing@gmail.com>
LABEL		description="Felhő Container"
RUN		yum install -y httpd && \
		yum clean all
COPY		./Felho/index.html /var/www/html/
		./Felho/adsl.png /var/www/html/
EXPOSE		80
CMD		["httpd", "-D", "FOREGROUND"]